fixed logback files
eventuate-examples/es-kanban-board pull request #5
Opened 2016-10-07 18:31 UTC by dartpopikyardo

2016-10-07 21:51 UTC, cer requested changes

2016-10-07 21:51 UTC, cer commented on java-server/api-gateway-service/src/main/resources/logback.xml
> -    <logger name="io.eventuate.client.java" level='info'>
`io.eventuate.client.java` can probably stay

2016-10-07 21:51 UTC, cer commented on java-server/api-gateway-service/src/main/resources/logback.xml
> +    <logger name="io.eventuate.activity" level='info'>
`io.eventuate.activity` needs to be debug level.

2016-10-10 07:53 UTC, dartpopikyardo commented on java-server/api-gateway-service/src/main/resources/logback.xml
> +    <logger name="io.eventuate.activity" level='info'>
fixed

2016-10-10 07:53 UTC, dartpopikyardo commented on java-server/api-gateway-service/src/main/resources/logback.xml
> -    <logger name="io.eventuate.client.java" level='info'>
fixed

2016-10-11 20:55 UTC, merged